/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.document.model;
// Generated Mar 3, 2014 5:25:27 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.core.model.Organization;
import org.openeos.erp.document.model.list.DocumentTypeTargetType;
import org.openeos.numeration.model.Sequence;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * DocumentType generated by hbm2java
 */
@Entity
@Table(name="c_doctype"
)
public class DocumentType  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_FINAL_SEQUENCE = "finalSequence";
     public static final String PROPERTY_DRAFT_SEQUENCE = "draftSequence";
     public static final String PROPERTY_TARGET_TYPE = "targetType";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_DOC_NO_CONTROLLED = "docNoControlled";

     private String id;
     private Organization organization;
     private Sequence finalSequence;
     private Sequence draftSequence;
     private DocumentTypeTargetType targetType;
     private String name;
     private String description;
     private boolean docNoControlled;

    public DocumentType() {
    }

	
    public DocumentType(Organization organization, DocumentTypeTargetType targetType, String name, boolean docNoControlled) {
        this.organization = organization;
        this.targetType = targetType;
        this.name = name;
        this.docNoControlled = docNoControlled;
    }
    public DocumentType(Organization organization, Sequence finalSequence, Sequence draftSequence, DocumentTypeTargetType targetType, String name, String description, boolean docNoControlled) {
       this.organization = organization;
       this.finalSequence = finalSequence;
       this.draftSequence = draftSequence;
       this.targetType = targetType;
       this.name = name;
       this.description = description;
       this.docNoControlled = docNoControlled;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="c_doctype_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ad_org_id", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="final_sequence_id")
    public Sequence getFinalSequence() {
        return this.finalSequence;
    }
    
    public void setFinalSequence(Sequence finalSequence) {
        this.finalSequence = finalSequence;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="draft_sequence_id")
    public Sequence getDraftSequence() {
        return this.draftSequence;
    }
    
    public void setDraftSequence(Sequence draftSequence) {
        this.draftSequence = draftSequence;
    }

    
    @Column(name="targettype", nullable=false)
    public DocumentTypeTargetType getTargetType() {
        return this.targetType;
    }
    
    public void setTargetType(DocumentTypeTargetType targetType) {
        this.targetType = targetType;
    }

    
    @Column(name="name", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="docnocontrolled", nullable=false)
    public boolean isDocNoControlled() {
        return this.docNoControlled;
    }
    
    public void setDocNoControlled(boolean docNoControlled) {
        this.docNoControlled = docNoControlled;
    }




}


