/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.attachments.model;
// Generated Apr 1, 2014 11:02:50 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name="ATT_ATTACHMENT"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ENTITY_CLASS", "ENTITY_ID", "NAME"}) 
)
public class Attachment  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_ENTITY_CLASS = "entityClass";
     public static final String PROPERTY_ENTITY_ID = "entityId";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_CREATION_DATE = "creationDate";
     public static final String PROPERTY_MODIFIED_DATE = "modifiedDate";
     public static final String PROPERTY_ATTACHMENT_TYPE = "attachmentType";
     public static final String PROPERTY_MIME_TYPE = "mimeType";
     public static final String PROPERTY_CONTENT = "content";

     private String id;
     private String entityClass;
     private String entityId;
     private String name;
     private Date creationDate;
     private Date modifiedDate;
     private String attachmentType;
     private String mimeType;
     private Blob content;

    public Attachment() {
    }

	
    public Attachment(String entityClass, String entityId, String name, Date creationDate, Date modifiedDate, String attachmentType, String mimeType) {
        this.entityClass = entityClass;
        this.entityId = entityId;
        this.name = name;
        this.creationDate = creationDate;
        this.modifiedDate = modifiedDate;
        this.attachmentType = attachmentType;
        this.mimeType = mimeType;
    }
    public Attachment(String entityClass, String entityId, String name, Date creationDate, Date modifiedDate, String attachmentType, String mimeType, Blob content) {
       this.entityClass = entityClass;
       this.entityId = entityId;
       this.name = name;
       this.creationDate = creationDate;
       this.modifiedDate = modifiedDate;
       this.attachmentType = attachmentType;
       this.mimeType = mimeType;
       this.content = content;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ATT_ATTACHMENT_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="ENTITY_CLASS", nullable=false)
    public String getEntityClass() {
        return this.entityClass;
    }
    
    public void setEntityClass(String entityClass) {
        this.entityClass = entityClass;
    }

    
    @Column(name="ENTITY_ID", nullable=false, length=32)
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_DATE", nullable=false, length=29)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_DATE", nullable=false, length=29)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="ATTACHMENT_TYPE", nullable=false)
    public String getAttachmentType() {
        return this.attachmentType;
    }
    
    public void setAttachmentType(String attachmentType) {
        this.attachmentType = attachmentType;
    }

    
    @Column(name="MIME_TYPE", nullable=false)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    
    @Column(name="CONTENT")
    public Blob getContent() {
        return this.content;
    }
    
    public void setContent(Blob content) {
        this.content = content;
    }




}


