/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.core.model;
// Generated Apr 22, 2014 5:16:14 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * BPLocation generated by hbm2java
 */
@Entity
@Table(name="C_BPARTNER_LOCATION"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class BPLocation  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_BUSINESS_PARTNER = "businessPartner";
     public static final String PROPERTY_LOCATION = "location";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_BILL_TO = "billTo";

     private String id;
     private Organization organization;
     private BusinessPartner businessPartner;
     private Location location;
     private String name;
     private boolean billTo;

    public BPLocation() {
    }

	
    public BPLocation(Organization organization, BusinessPartner businessPartner, String name, boolean billTo) {
        this.organization = organization;
        this.businessPartner = businessPartner;
        this.name = name;
        this.billTo = billTo;
    }
    public BPLocation(Organization organization, BusinessPartner businessPartner, Location location, String name, boolean billTo) {
       this.organization = organization;
       this.businessPartner = businessPartner;
       this.location = location;
       this.name = name;
       this.billTo = billTo;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_BPARTNER_LOCATION_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_BPARTNER_ID", nullable=false)
    public BusinessPartner getBusinessPartner() {
        return this.businessPartner;
    }
    
    public void setBusinessPartner(BusinessPartner businessPartner) {
        this.businessPartner = businessPartner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_LOCATION_ID")
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    
    @Column(name="NAME", unique=true, nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ISBILLTO", nullable=false)
    public boolean isBillTo() {
        return this.billTo;
    }
    
    public void setBillTo(boolean billTo) {
        this.billTo = billTo;
    }




}


