/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.core.model;
// Generated Apr 22, 2014 5:16:14 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * BusinessPartner generated by hbm2java
 */
@Entity
@Table(name="C_BPARTNER"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"AD_ORG_ID", "NAME"}), @UniqueConstraint(columnNames={"AD_ORG_ID", "VALUE"}), @UniqueConstraint(columnNames="NAME"), @UniqueConstraint(columnNames="VALUE")} 
)
public class BusinessPartner  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_VALUE = "value";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_NAME2 = "name2";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_TAXID = "taxid";
     public static final String PROPERTY__B_P_LOCATIONS = "BPLocations";

     private String id;
     private Organization organization;
     private String value;
     private String name;
     private String name2;
     private String description;
     private String taxid;
     private Set<BPLocation> BPLocations = new HashSet<BPLocation>(0);

    public BusinessPartner() {
    }

	
    public BusinessPartner(Organization organization, String value, String name) {
        this.organization = organization;
        this.value = value;
        this.name = name;
    }
    public BusinessPartner(Organization organization, String value, String name, String name2, String description, String taxid, Set<BPLocation> BPLocations) {
       this.organization = organization;
       this.value = value;
       this.name = name;
       this.name2 = name2;
       this.description = description;
       this.taxid = taxid;
       this.BPLocations = BPLocations;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_BPARTNER_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    
    @Column(name="VALUE", unique=true, nullable=false, length=40)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="NAME", unique=true, nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME2", length=60)
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="TAXID", length=20)
    public String getTaxid() {
        return this.taxid;
    }
    
    public void setTaxid(String taxid) {
        this.taxid = taxid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="businessPartner")
    public Set<BPLocation> getBPLocations() {
        return this.BPLocations;
    }
    
    public void setBPLocations(Set<BPLocation> BPLocations) {
        this.BPLocations = BPLocations;
    }




}


