/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.core.model;
// Generated Apr 22, 2014 5:16:14 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="C_LOCATION"
)
public class Location  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_COUNTRY = "country";
     public static final String PROPERTY_REGION = "region";
     public static final String PROPERTY_ADDRESS1 = "address1";
     public static final String PROPERTY_ADDRESS2 = "address2";
     public static final String PROPERTY_CITY = "city";
     public static final String PROPERTY_POSTAL = "postal";
     public static final String PROPERTY_POSTAL_ADD = "postalAdd";
     public static final String PROPERTY_REGIONNAME = "regionname";
     public static final String PROPERTY__B_P_LOCATIONS = "BPLocations";

     private String id;
     private Country country;
     private Region region;
     private String address1;
     private String address2;
     private String city;
     private String postal;
     private String postalAdd;
     private String regionname;
     private Set<BPLocation> BPLocations = new HashSet<BPLocation>(0);

    public Location() {
    }

	
    public Location(Country country) {
        this.country = country;
    }
    public Location(Country country, Region region, String address1, String address2, String city, String postal, String postalAdd, String regionname, Set<BPLocation> BPLocations) {
       this.country = country;
       this.region = region;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.postal = postal;
       this.postalAdd = postalAdd;
       this.regionname = regionname;
       this.BPLocations = BPLocations;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_LOCATION_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_COUNTRY_ID", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_REGION_ID")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }

    
    @Column(name="ADDRESS1", length=60)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="ADDRESS2", length=60)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="CITY", length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="POSTAL", length=10)
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }

    
    @Column(name="POSTAL_ADD", length=10)
    public String getPostalAdd() {
        return this.postalAdd;
    }
    
    public void setPostalAdd(String postalAdd) {
        this.postalAdd = postalAdd;
    }

    
    @Column(name="REGIONNAME", length=40)
    public String getRegionname() {
        return this.regionname;
    }
    
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<BPLocation> getBPLocations() {
        return this.BPLocations;
    }
    
    public void setBPLocations(Set<BPLocation> BPLocations) {
        this.BPLocations = BPLocations;
    }




}


