/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.sales.model;
// Generated Mar 29, 2014 10:10:27 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * SalesInvoiceTax generated by hbm2java
 */
@Entity
@Table(name="C_SALES_INVOICE_TAX"
)
public class SalesInvoiceTax  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_SALES_INVOICE = "salesInvoice";
     public static final String PROPERTY_TAXBASEAMT = "taxbaseamt";
     public static final String PROPERTY_TAXAMT = "taxamt";
     public static final String PROPERTY_LINE = "line";

     private String id;
     private SalesInvoice salesInvoice;
     private BigDecimal taxbaseamt;
     private BigDecimal taxamt;
     private Integer line;

    public SalesInvoiceTax() {
    }

	
    public SalesInvoiceTax(SalesInvoice salesInvoice, BigDecimal taxbaseamt, BigDecimal taxamt) {
        this.salesInvoice = salesInvoice;
        this.taxbaseamt = taxbaseamt;
        this.taxamt = taxamt;
    }
    public SalesInvoiceTax(SalesInvoice salesInvoice, BigDecimal taxbaseamt, BigDecimal taxamt, Integer line) {
       this.salesInvoice = salesInvoice;
       this.taxbaseamt = taxbaseamt;
       this.taxamt = taxamt;
       this.line = line;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_SALES_INVOICE_TAX_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_SALES_INVOICE_ID", nullable=false)
    public SalesInvoice getSalesInvoice() {
        return this.salesInvoice;
    }
    
    public void setSalesInvoice(SalesInvoice salesInvoice) {
        this.salesInvoice = salesInvoice;
    }

    
    @Column(name="TAXBASEAMT", nullable=false, precision=31, scale=8)
    public BigDecimal getTaxbaseamt() {
        return this.taxbaseamt;
    }
    
    public void setTaxbaseamt(BigDecimal taxbaseamt) {
        this.taxbaseamt = taxbaseamt;
    }

    
    @Column(name="TAXAMT", nullable=false, precision=31, scale=8)
    public BigDecimal getTaxamt() {
        return this.taxamt;
    }
    
    public void setTaxamt(BigDecimal taxamt) {
        this.taxamt = taxamt;
    }

    
    @Column(name="LINE")
    public Integer getLine() {
        return this.line;
    }
    
    public void setLine(Integer line) {
        this.line = line;
    }




}


