/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.sales.model;
// Generated Mar 29, 2014 10:10:27 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.core.model.BPLocation;
import org.openeos.erp.core.model.BusinessPartner;
import org.openeos.erp.core.model.Organization;
import org.openeos.erp.document.model.DocumentType;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * SalesInvoice generated by hbm2java
 */
@Entity
@Table(name="C_SALES_INVOICE"
)
public class SalesInvoice  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY__B_P_LOCATION = "BPLocation";
     public static final String PROPERTY_BUSINESS_PARTNER = "businessPartner";
     public static final String PROPERTY_DOCUMENT_TYPE = "documentType";
     public static final String PROPERTY_DOCUMENT_NO = "documentNo";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_TRANSACTION_DATE = "transactionDate";
     public static final String PROPERTY_GRANDTOTAL = "grandtotal";
     public static final String PROPERTY_TAXDATE = "taxdate";
     public static final String PROPERTY_DRAFT = "draft";
     public static final String PROPERTY_POSTED = "posted";
     public static final String PROPERTY_POSTED_WORKFLOW_ID = "postedWorkflowId";
     public static final String PROPERTY_SALES_INVOICE_TAXES = "salesInvoiceTaxes";

     private String id;
     private Organization organization;
     private BPLocation BPLocation;
     private BusinessPartner businessPartner;
     private DocumentType documentType;
     private String documentNo;
     private String description;
     private Date transactionDate;
     private BigDecimal grandtotal;
     private Date taxdate;
     private boolean draft;
     private boolean posted;
     private String postedWorkflowId;
     private Set<SalesInvoiceTax> salesInvoiceTaxes = new HashSet<SalesInvoiceTax>(0);

    public SalesInvoice() {
    }

	
    public SalesInvoice(Organization organization, BPLocation BPLocation, BusinessPartner businessPartner, DocumentType documentType, String documentNo, Date transactionDate, BigDecimal grandtotal, Date taxdate, boolean draft, boolean posted) {
        this.organization = organization;
        this.BPLocation = BPLocation;
        this.businessPartner = businessPartner;
        this.documentType = documentType;
        this.documentNo = documentNo;
        this.transactionDate = transactionDate;
        this.grandtotal = grandtotal;
        this.taxdate = taxdate;
        this.draft = draft;
        this.posted = posted;
    }
    public SalesInvoice(Organization organization, BPLocation BPLocation, BusinessPartner businessPartner, DocumentType documentType, String documentNo, String description, Date transactionDate, BigDecimal grandtotal, Date taxdate, boolean draft, boolean posted, String postedWorkflowId, Set<SalesInvoiceTax> salesInvoiceTaxes) {
       this.organization = organization;
       this.BPLocation = BPLocation;
       this.businessPartner = businessPartner;
       this.documentType = documentType;
       this.documentNo = documentNo;
       this.description = description;
       this.transactionDate = transactionDate;
       this.grandtotal = grandtotal;
       this.taxdate = taxdate;
       this.draft = draft;
       this.posted = posted;
       this.postedWorkflowId = postedWorkflowId;
       this.salesInvoiceTaxes = salesInvoiceTaxes;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_SALES_INVOICE_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_BPARTNER_LOCATION_ID", nullable=false)
    public BPLocation getBPLocation() {
        return this.BPLocation;
    }
    
    public void setBPLocation(BPLocation BPLocation) {
        this.BPLocation = BPLocation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_BPARTNER_ID", nullable=false)
    public BusinessPartner getBusinessPartner() {
        return this.businessPartner;
    }
    
    public void setBusinessPartner(BusinessPartner businessPartner) {
        this.businessPartner = businessPartner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_DOCTYPE_ID", nullable=false)
    public DocumentType getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

    
    @Column(name="DOCUMENTNO", nullable=false, length=30)
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRANSACTIONDATE", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="GRANDTOTAL", nullable=false, precision=31, scale=8)
    public BigDecimal getGrandtotal() {
        return this.grandtotal;
    }
    
    public void setGrandtotal(BigDecimal grandtotal) {
        this.grandtotal = grandtotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TAXDATE", nullable=false, length=10)
    public Date getTaxdate() {
        return this.taxdate;
    }
    
    public void setTaxdate(Date taxdate) {
        this.taxdate = taxdate;
    }

    
    @Column(name="DRAFT", nullable=false)
    public boolean isDraft() {
        return this.draft;
    }
    
    public void setDraft(boolean draft) {
        this.draft = draft;
    }

    
    @Column(name="POSTED", nullable=false)
    public boolean isPosted() {
        return this.posted;
    }
    
    public void setPosted(boolean posted) {
        this.posted = posted;
    }

    
    @Column(name="POSTED_WORKFLOW_ID", length=32)
    public String getPostedWorkflowId() {
        return this.postedWorkflowId;
    }
    
    public void setPostedWorkflowId(String postedWorkflowId) {
        this.postedWorkflowId = postedWorkflowId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salesInvoice")
    public Set<SalesInvoiceTax> getSalesInvoiceTaxes() {
        return this.salesInvoiceTaxes;
    }
    
    public void setSalesInvoiceTaxes(Set<SalesInvoiceTax> salesInvoiceTaxes) {
        this.salesInvoiceTaxes = salesInvoiceTaxes;
    }




}


