/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.sales.model;
// Generated Mar 29, 2014 10:10:27 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.core.model.Organization;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TaxCategory generated by hbm2java
 */
@Entity
@Table(name="C_TAXCATEGORY"
)
public class TaxCategory  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_TAXES = "taxes";

     private String id;
     private Organization organization;
     private String name;
     private String description;
     private Set<Tax> taxes = new HashSet<Tax>(0);

    public TaxCategory() {
    }

	
    public TaxCategory(Organization organization, String name) {
        this.organization = organization;
        this.name = name;
    }
    public TaxCategory(Organization organization, String name, String description, Set<Tax> taxes) {
       this.organization = organization;
       this.name = name;
       this.description = description;
       this.taxes = taxes;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_TAXCATEGORY_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    
    @Column(name="NAME", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taxCategory")
    public Set<Tax> getTaxes() {
        return this.taxes;
    }
    
    public void setTaxes(Set<Tax> taxes) {
        this.taxes = taxes;
    }




}


