/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.jbpm.integration.model;
// Generated 26-jun-2013 15:37:46 by Hibernate Tools 3.2.4.GA
// Template generated from org.openeos.hibernate.hbm2java


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * DroolsSession generated by hbm2java
 */
@Entity
@Table(name="drools_session"
    , uniqueConstraints = @UniqueConstraint(columnNames="drools_internal_id") 
)
public class DroolsSession  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_DROOLS_INTERNAL_ID = "droolsInternalId";
     public static final String PROPERTY_START_DATE = "startDate";
     public static final String PROPERTY_LAST_MODIFICATION_DATE = "lastModificationDate";
     public static final String PROPERTY_BYTES = "bytes";

     private String id;
     private int droolsInternalId;
     private Date startDate;
     private Date lastModificationDate;
     private byte[] bytes;

    public DroolsSession() {
    }

	
    public DroolsSession(int droolsInternalId, Date startDate) {
        this.droolsInternalId = droolsInternalId;
        this.startDate = startDate;
    }
    public DroolsSession(int droolsInternalId, Date startDate, Date lastModificationDate, byte[] bytes) {
       this.droolsInternalId = droolsInternalId;
       this.startDate = startDate;
       this.lastModificationDate = lastModificationDate;
       this.bytes = bytes;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="drools_session_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="drools_internal_id", unique=true, nullable=false)
    public int getDroolsInternalId() {
        return this.droolsInternalId;
    }
    
    public void setDroolsInternalId(int droolsInternalId) {
        this.droolsInternalId = droolsInternalId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=35)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modification_date", length=35)
    public Date getLastModificationDate() {
        return this.lastModificationDate;
    }
    
    public void setLastModificationDate(Date lastModificationDate) {
        this.lastModificationDate = lastModificationDate;
    }

    
    @Column(name="bytes")
    public byte[] getBytes() {
        return this.bytes;
    }
    
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }




}


