/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.jbpm.integration.model;
// Generated 26-jun-2013 15:37:46 by Hibernate Tools 3.2.4.GA
// Template generated from org.openeos.hibernate.hbm2java


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * JbpmProcessInstanceEventType generated by hbm2java
 */
@Entity
@Table(name="jbpm_process_instance_event_type"
    , uniqueConstraints = @UniqueConstraint(columnNames={"jbpm_process_instance_id", "event_type"}) 
)
public class JbpmProcessInstanceEventType  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_JBPM_PROCESS_INSTANCE = "jbpmProcessInstance";
     public static final String PROPERTY_EVENT_TYPE = "eventType";

     private String id;
     private JbpmProcessInstance jbpmProcessInstance;
     private String eventType;

    public JbpmProcessInstanceEventType() {
    }

    public JbpmProcessInstanceEventType(JbpmProcessInstance jbpmProcessInstance, String eventType) {
       this.jbpmProcessInstance = jbpmProcessInstance;
       this.eventType = eventType;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="jbpm_process_instance_event_type_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jbpm_process_instance_id", nullable=false)
    public JbpmProcessInstance getJbpmProcessInstance() {
        return this.jbpmProcessInstance;
    }
    
    public void setJbpmProcessInstance(JbpmProcessInstance jbpmProcessInstance) {
        this.jbpmProcessInstance = jbpmProcessInstance;
    }

    
    @Column(name="event_type", nullable=false)
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }




}


