/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.jbpm.integration.model;
// Generated 26-jun-2013 15:37:46 by Hibernate Tools 3.2.4.GA
// Template generated from org.openeos.hibernate.hbm2java


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * WorkItem generated by hbm2java
 */
@Entity
@Table(name="drools_work_item"
    , uniqueConstraints = @UniqueConstraint(columnNames="drools_internal_id") 
)
public class WorkItem  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_DROOLS_INTERNAL_ID = "droolsInternalId";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_CREATION_DATE = "creationDate";
     public static final String PROPERTY_PROCESS_INSTANCE_ID = "processInstanceId";
     public static final String PROPERTY_STATE = "state";
     public static final String PROPERTY_BYTES = "bytes";

     private String id;
     private long droolsInternalId;
     private String name;
     private Date creationDate;
     private long processInstanceId;
     private long state;
     private byte[] bytes;

    public WorkItem() {
    }

	
    public WorkItem(long droolsInternalId, String name, Date creationDate, long processInstanceId, long state) {
        this.droolsInternalId = droolsInternalId;
        this.name = name;
        this.creationDate = creationDate;
        this.processInstanceId = processInstanceId;
        this.state = state;
    }
    public WorkItem(long droolsInternalId, String name, Date creationDate, long processInstanceId, long state, byte[] bytes) {
       this.droolsInternalId = droolsInternalId;
       this.name = name;
       this.creationDate = creationDate;
       this.processInstanceId = processInstanceId;
       this.state = state;
       this.bytes = bytes;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="drools_work_item_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="drools_internal_id", unique=true, nullable=false)
    public long getDroolsInternalId() {
        return this.droolsInternalId;
    }
    
    public void setDroolsInternalId(long droolsInternalId) {
        this.droolsInternalId = droolsInternalId;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=35)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="process_instance_id", nullable=false)
    public long getProcessInstanceId() {
        return this.processInstanceId;
    }
    
    public void setProcessInstanceId(long processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    
    @Column(name="state", nullable=false)
    public long getState() {
        return this.state;
    }
    
    public void setState(long state) {
        this.state = state;
    }

    
    @Column(name="bytes")
    public byte[] getBytes() {
        return this.bytes;
    }
    
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }




}


