/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.wf.model;
// Generated Mar 14, 2014 12:12:59 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * Deployment generated by hbm2java
 */
@Entity
@Table(name="wf_deployment"
    , uniqueConstraints = @UniqueConstraint(columnNames={"value", "version"}) 
)
public class Deployment  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_VALUE = "value";
     public static final String PROPERTY_VERSION = "version";
     public static final String PROPERTY_DEPLOYMENTDATE = "deploymentdate";
     public static final String PROPERTY_WORKFLOW_DEFINITIONS = "workflowDefinitions";

     private String id;
     private String value;
     private String version;
     private Date deploymentdate;
     private Set<WorkflowDefinition> workflowDefinitions = new HashSet<WorkflowDefinition>(0);

    public Deployment() {
    }

	
    public Deployment(String value, Date deploymentdate) {
        this.value = value;
        this.deploymentdate = deploymentdate;
    }
    public Deployment(String value, String version, Date deploymentdate, Set<WorkflowDefinition> workflowDefinitions) {
       this.value = value;
       this.version = version;
       this.deploymentdate = deploymentdate;
       this.workflowDefinitions = workflowDefinitions;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="wf_deployment_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="value", nullable=false, length=60)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="version", length=60)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deploymentdate", nullable=false, length=35)
    public Date getDeploymentdate() {
        return this.deploymentdate;
    }
    
    public void setDeploymentdate(Date deploymentdate) {
        this.deploymentdate = deploymentdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="deployment")
    public Set<WorkflowDefinition> getWorkflowDefinitions() {
        return this.workflowDefinitions;
    }
    
    public void setWorkflowDefinitions(Set<WorkflowDefinition> workflowDefinitions) {
        this.workflowDefinitions = workflowDefinitions;
    }




}


