/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.wf.model;
// Generated Mar 14, 2014 12:12:59 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * WorkflowDefinition generated by hbm2java
 */
@Entity
@Table(name="wf_definition"
    , uniqueConstraints = @UniqueConstraint(columnNames={"value", "version"}) 
)
public class WorkflowDefinition  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_DEPLOYMENT = "deployment";
     public static final String PROPERTY_VALUE = "value";
     public static final String PROPERTY_VERSION = "version";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_CHECKSUM = "checksum";
     public static final String PROPERTY_WORKFLOW_DEFINITION_CONTENT = "workflowDefinitionContent";

     private String id;
     private Deployment deployment;
     private String value;
     private String version;
     private String name;
     private String checksum;
     private WorkflowDefinitionContent workflowDefinitionContent;

    public WorkflowDefinition() {
    }

	
    public WorkflowDefinition(Deployment deployment, String value, String version, String checksum) {
        this.deployment = deployment;
        this.value = value;
        this.version = version;
        this.checksum = checksum;
    }
    public WorkflowDefinition(Deployment deployment, String value, String version, String name, String checksum, WorkflowDefinitionContent workflowDefinitionContent) {
       this.deployment = deployment;
       this.value = value;
       this.version = version;
       this.name = name;
       this.checksum = checksum;
       this.workflowDefinitionContent = workflowDefinitionContent;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="wf_definition_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wf_deployment_id", nullable=false)
    public Deployment getDeployment() {
        return this.deployment;
    }
    
    public void setDeployment(Deployment deployment) {
        this.deployment = deployment;
    }

    
    @Column(name="value", nullable=false, length=60)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="version", nullable=false, length=60)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="checksum", nullable=false)
    public String getChecksum() {
        return this.checksum;
    }
    
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="workflowDefinition")
    public WorkflowDefinitionContent getWorkflowDefinitionContent() {
        return this.workflowDefinitionContent;
    }
    
    public void setWorkflowDefinitionContent(WorkflowDefinitionContent workflowDefinitionContent) {
        this.workflowDefinitionContent = workflowDefinitionContent;
    }




}


