/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtYear generated by hbm2java
 */
@Entity
@Table(name="C_YEAR"
    , uniqueConstraints = @UniqueConstraint(columnNames={"C_CALENDAR_ID", "NAME"}) 
)
public class FinancialMgmtYear  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_CALENDAR = "financialMgmtCalendar";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_FINANCIAL_MGMT_PERIODS = "financialMgmtPeriods";

     private String id;
     private FinancialMgmtCalendar financialMgmtCalendar;
     private String name;
     private String description;
     private Set<FinancialMgmtPeriod> financialMgmtPeriods = new HashSet<FinancialMgmtPeriod>(0);

    public FinancialMgmtYear() {
    }

	
    public FinancialMgmtYear(FinancialMgmtCalendar financialMgmtCalendar, String name) {
        this.financialMgmtCalendar = financialMgmtCalendar;
        this.name = name;
    }
    public FinancialMgmtYear(FinancialMgmtCalendar financialMgmtCalendar, String name, String description, Set<FinancialMgmtPeriod> financialMgmtPeriods) {
       this.financialMgmtCalendar = financialMgmtCalendar;
       this.name = name;
       this.description = description;
       this.financialMgmtPeriods = financialMgmtPeriods;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_YEAR_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_CALENDAR_ID", nullable=false)
    public FinancialMgmtCalendar getFinancialMgmtCalendar() {
        return this.financialMgmtCalendar;
    }
    
    public void setFinancialMgmtCalendar(FinancialMgmtCalendar financialMgmtCalendar) {
        this.financialMgmtCalendar = financialMgmtCalendar;
    }

    
    @Column(name="NAME", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="financialMgmtYear")
    public Set<FinancialMgmtPeriod> getFinancialMgmtPeriods() {
        return this.financialMgmtPeriods;
    }
    
    public void setFinancialMgmtPeriods(Set<FinancialMgmtPeriod> financialMgmtPeriods) {
        this.financialMgmtPeriods = financialMgmtPeriods;
    }




}


