/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtElementValue generated by hbm2java
 */
@Entity
@Table(name="C_ELEMENTVALUE"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"C_ELEMENT_ID", "NAME"}), @UniqueConstraint(columnNames={"C_ELEMENT_ID", "VALUE"})} 
)
public class FinancialMgmtElementValue  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_ELEMENT = "financialMgmtElement";
     public static final String PROPERTY_VALUE = "value";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_DESCRIPTION = "description";

     private String id;
     private FinancialMgmtElement financialMgmtElement;
     private String value;
     private String name;
     private String description;

    public FinancialMgmtElementValue() {
    }

	
    public FinancialMgmtElementValue(FinancialMgmtElement financialMgmtElement, String value, String name) {
        this.financialMgmtElement = financialMgmtElement;
        this.value = value;
        this.name = name;
    }
    public FinancialMgmtElementValue(FinancialMgmtElement financialMgmtElement, String value, String name, String description) {
       this.financialMgmtElement = financialMgmtElement;
       this.value = value;
       this.name = name;
       this.description = description;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_ELEMENTVALUE_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_ELEMENT_ID", nullable=false)
    public FinancialMgmtElement getFinancialMgmtElement() {
        return this.financialMgmtElement;
    }
    
    public void setFinancialMgmtElement(FinancialMgmtElement financialMgmtElement) {
        this.financialMgmtElement = financialMgmtElement;
    }

    
    @Column(name="VALUE", nullable=false, length=40)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="NAME", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


