/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.core.model.Organization;
import org.openeos.erp.document.model.DocumentType;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtGLBatch generated by hbm2java
 */
@Entity
@Table(name="GL_JOURNALBATCH"
    , uniqueConstraints = @UniqueConstraint(columnNames={"AD_ORG_ID", "DOCUMENTNO"}) 
)
public class FinancialMgmtGLBatch  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_G_L_CATEGORY = "financialMgmtGLCategory";
     public static final String PROPERTY_FINANCIAL_MGMT_PERIOD = "financialMgmtPeriod";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_DOCUMENT_TYPE = "documentType";
     public static final String PROPERTY_DOCUMENT_NO = "documentNo";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_TRANSACTION_DATE = "transactionDate";
     public static final String PROPERTY_ACCT_DATE = "acctDate";
     public static final String PROPERTY_TOTAL_D_R = "totalDR";
     public static final String PROPERTY_TOTAL_C_R = "totalCR";
     public static final String PROPERTY_FINANCIAL_MGMT_G_L_JOURNALS = "financialMgmtGLJournals";

     private String id;
     private FinancialMgmtGLCategory financialMgmtGLCategory;
     private FinancialMgmtPeriod financialMgmtPeriod;
     private Organization organization;
     private DocumentType documentType;
     private String documentNo;
     private String description;
     private Date transactionDate;
     private Date acctDate;
     private BigDecimal totalDR;
     private BigDecimal totalCR;
     private Set<FinancialMgmtGLJournal> financialMgmtGLJournals = new HashSet<FinancialMgmtGLJournal>(0);

    public FinancialMgmtGLBatch() {
    }

	
    public FinancialMgmtGLBatch(FinancialMgmtGLCategory financialMgmtGLCategory, Organization organization, DocumentType documentType, String documentNo, Date transactionDate, Date acctDate, BigDecimal totalDR, BigDecimal totalCR) {
        this.financialMgmtGLCategory = financialMgmtGLCategory;
        this.organization = organization;
        this.documentType = documentType;
        this.documentNo = documentNo;
        this.transactionDate = transactionDate;
        this.acctDate = acctDate;
        this.totalDR = totalDR;
        this.totalCR = totalCR;
    }
    public FinancialMgmtGLBatch(FinancialMgmtGLCategory financialMgmtGLCategory, FinancialMgmtPeriod financialMgmtPeriod, Organization organization, DocumentType documentType, String documentNo, String description, Date transactionDate, Date acctDate, BigDecimal totalDR, BigDecimal totalCR, Set<FinancialMgmtGLJournal> financialMgmtGLJournals) {
       this.financialMgmtGLCategory = financialMgmtGLCategory;
       this.financialMgmtPeriod = financialMgmtPeriod;
       this.organization = organization;
       this.documentType = documentType;
       this.documentNo = documentNo;
       this.description = description;
       this.transactionDate = transactionDate;
       this.acctDate = acctDate;
       this.totalDR = totalDR;
       this.totalCR = totalCR;
       this.financialMgmtGLJournals = financialMgmtGLJournals;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="GL_JOURNALBATCH_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GL_CATEGORY_ID", nullable=false)
    public FinancialMgmtGLCategory getFinancialMgmtGLCategory() {
        return this.financialMgmtGLCategory;
    }
    
    public void setFinancialMgmtGLCategory(FinancialMgmtGLCategory financialMgmtGLCategory) {
        this.financialMgmtGLCategory = financialMgmtGLCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_PERIOD_ID")
    public FinancialMgmtPeriod getFinancialMgmtPeriod() {
        return this.financialMgmtPeriod;
    }
    
    public void setFinancialMgmtPeriod(FinancialMgmtPeriod financialMgmtPeriod) {
        this.financialMgmtPeriod = financialMgmtPeriod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_DOCTYPE_ID", nullable=false)
    public DocumentType getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

    
    @Column(name="DOCUMENTNO", nullable=false, length=30)
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRANSACTIONDATE", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACCTDATE", nullable=false, length=10)
    public Date getAcctDate() {
        return this.acctDate;
    }
    
    public void setAcctDate(Date acctDate) {
        this.acctDate = acctDate;
    }

    
    @Column(name="TOTALDR", nullable=false, precision=31, scale=8)
    public BigDecimal getTotalDR() {
        return this.totalDR;
    }
    
    public void setTotalDR(BigDecimal totalDR) {
        this.totalDR = totalDR;
    }

    
    @Column(name="TOTALCR", nullable=false, precision=31, scale=8)
    public BigDecimal getTotalCR() {
        return this.totalCR;
    }
    
    public void setTotalCR(BigDecimal totalCR) {
        this.totalCR = totalCR;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="financialMgmtGLBatch")
    public Set<FinancialMgmtGLJournal> getFinancialMgmtGLJournals() {
        return this.financialMgmtGLJournals;
    }
    
    public void setFinancialMgmtGLJournals(Set<FinancialMgmtGLJournal> financialMgmtGLJournals) {
        this.financialMgmtGLJournals = financialMgmtGLJournals;
    }




}


