/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.core.model.Organization;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtAccountingCombination generated by hbm2java
 */
@Entity
@Table(name="C_VALIDCOMBINATION"
)
public class FinancialMgmtAccountingCombination  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_ELEMENT_VALUE = "financialMgmtElementValue";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_FINANCIAL_MGMT_ACCT_SCHEMA = "financialMgmtAcctSchema";
     public static final String PROPERTY_ALIAS = "alias";
     public static final String PROPERTY_COMBINATION = "combination";
     public static final String PROPERTY_DESCRIPTION = "description";

     private String id;
     private FinancialMgmtElementValue financialMgmtElementValue;
     private Organization organization;
     private FinancialMgmtAcctSchema financialMgmtAcctSchema;
     private String alias;
     private String combination;
     private String description;

    public FinancialMgmtAccountingCombination() {
    }

	
    public FinancialMgmtAccountingCombination(FinancialMgmtElementValue financialMgmtElementValue, Organization organization, FinancialMgmtAcctSchema financialMgmtAcctSchema, String alias) {
        this.financialMgmtElementValue = financialMgmtElementValue;
        this.organization = organization;
        this.financialMgmtAcctSchema = financialMgmtAcctSchema;
        this.alias = alias;
    }
    public FinancialMgmtAccountingCombination(FinancialMgmtElementValue financialMgmtElementValue, Organization organization, FinancialMgmtAcctSchema financialMgmtAcctSchema, String alias, String combination, String description) {
       this.financialMgmtElementValue = financialMgmtElementValue;
       this.organization = organization;
       this.financialMgmtAcctSchema = financialMgmtAcctSchema;
       this.alias = alias;
       this.combination = combination;
       this.description = description;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_VALIDCOMBINATION_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_ID", nullable=false)
    public FinancialMgmtElementValue getFinancialMgmtElementValue() {
        return this.financialMgmtElementValue;
    }
    
    public void setFinancialMgmtElementValue(FinancialMgmtElementValue financialMgmtElementValue) {
        this.financialMgmtElementValue = financialMgmtElementValue;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_ACCTSCHEMA_ID", nullable=false)
    public FinancialMgmtAcctSchema getFinancialMgmtAcctSchema() {
        return this.financialMgmtAcctSchema;
    }
    
    public void setFinancialMgmtAcctSchema(FinancialMgmtAcctSchema financialMgmtAcctSchema) {
        this.financialMgmtAcctSchema = financialMgmtAcctSchema;
    }

    
    @Column(name="ALIAS", nullable=false, length=40)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    
    @Column(name="COMBINATION", length=120)
    public String getCombination() {
        return this.combination;
    }
    
    public void setCombination(String combination) {
        this.combination = combination;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


