/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.core.model.Organization;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtAccountingFact generated by hbm2java
 */
@Entity
@Table(name="FACT_ACCT"
)
public class FinancialMgmtAccountingFact  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_G_L_CATEGORY = "financialMgmtGLCategory";
     public static final String PROPERTY_FINANCIAL_MGMT_ELEMENT_VALUE = "financialMgmtElementValue";
     public static final String PROPERTY_FINANCIAL_MGMT_PERIOD = "financialMgmtPeriod";
     public static final String PROPERTY_ORGANIZATION = "organization";
     public static final String PROPERTY_FINANCIAL_MGMT_ACCT_SCHEMA = "financialMgmtAcctSchema";
     public static final String PROPERTY_TRANSACTION_DATE = "transactionDate";
     public static final String PROPERTY_ACCT_DATE = "acctDate";
     public static final String PROPERTY_ENTITY_NAME = "entityName";
     public static final String PROPERTY_ENTITY_ID = "entityId";
     public static final String PROPERTY_AMT_ACCT_D_R = "amtAcctDR";
     public static final String PROPERTY_AMT_ACCT_C_R = "amtAcctCR";
     public static final String PROPERTY_FACT_ACCT_GROUP_ID = "factAcctGroupId";
     public static final String PROPERTY_SEQ_NO = "seqNo";

     private String id;
     private FinancialMgmtGLCategory financialMgmtGLCategory;
     private FinancialMgmtElementValue financialMgmtElementValue;
     private FinancialMgmtPeriod financialMgmtPeriod;
     private Organization organization;
     private FinancialMgmtAcctSchema financialMgmtAcctSchema;
     private Date transactionDate;
     private Date acctDate;
     private String entityName;
     private String entityId;
     private BigDecimal amtAcctDR;
     private BigDecimal amtAcctCR;
     private String factAcctGroupId;
     private int seqNo;

    public FinancialMgmtAccountingFact() {
    }

    public FinancialMgmtAccountingFact(FinancialMgmtGLCategory financialMgmtGLCategory, FinancialMgmtElementValue financialMgmtElementValue, FinancialMgmtPeriod financialMgmtPeriod, Organization organization, FinancialMgmtAcctSchema financialMgmtAcctSchema, Date transactionDate, Date acctDate, String entityName, String entityId, BigDecimal amtAcctDR, BigDecimal amtAcctCR, String factAcctGroupId, int seqNo) {
       this.financialMgmtGLCategory = financialMgmtGLCategory;
       this.financialMgmtElementValue = financialMgmtElementValue;
       this.financialMgmtPeriod = financialMgmtPeriod;
       this.organization = organization;
       this.financialMgmtAcctSchema = financialMgmtAcctSchema;
       this.transactionDate = transactionDate;
       this.acctDate = acctDate;
       this.entityName = entityName;
       this.entityId = entityId;
       this.amtAcctDR = amtAcctDR;
       this.amtAcctCR = amtAcctCR;
       this.factAcctGroupId = factAcctGroupId;
       this.seqNo = seqNo;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="FACT_ACCT_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GL_CATEGORY_ID", nullable=false)
    public FinancialMgmtGLCategory getFinancialMgmtGLCategory() {
        return this.financialMgmtGLCategory;
    }
    
    public void setFinancialMgmtGLCategory(FinancialMgmtGLCategory financialMgmtGLCategory) {
        this.financialMgmtGLCategory = financialMgmtGLCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_ID", nullable=false)
    public FinancialMgmtElementValue getFinancialMgmtElementValue() {
        return this.financialMgmtElementValue;
    }
    
    public void setFinancialMgmtElementValue(FinancialMgmtElementValue financialMgmtElementValue) {
        this.financialMgmtElementValue = financialMgmtElementValue;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_PERIOD_ID", nullable=false)
    public FinancialMgmtPeriod getFinancialMgmtPeriod() {
        return this.financialMgmtPeriod;
    }
    
    public void setFinancialMgmtPeriod(FinancialMgmtPeriod financialMgmtPeriod) {
        this.financialMgmtPeriod = financialMgmtPeriod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AD_ORG_ID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_ACCTSCHEMA_ID", nullable=false)
    public FinancialMgmtAcctSchema getFinancialMgmtAcctSchema() {
        return this.financialMgmtAcctSchema;
    }
    
    public void setFinancialMgmtAcctSchema(FinancialMgmtAcctSchema financialMgmtAcctSchema) {
        this.financialMgmtAcctSchema = financialMgmtAcctSchema;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRANSACTIONDATE", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACCTDATE", nullable=false, length=10)
    public Date getAcctDate() {
        return this.acctDate;
    }
    
    public void setAcctDate(Date acctDate) {
        this.acctDate = acctDate;
    }

    
    @Column(name="ENTITYNAME", nullable=false, length=60)
    public String getEntityName() {
        return this.entityName;
    }
    
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    
    @Column(name="ENTITYID", nullable=false, length=32)
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    
    @Column(name="AMTACCTDR", nullable=false, precision=31, scale=8)
    public BigDecimal getAmtAcctDR() {
        return this.amtAcctDR;
    }
    
    public void setAmtAcctDR(BigDecimal amtAcctDR) {
        this.amtAcctDR = amtAcctDR;
    }

    
    @Column(name="AMTACCTCR", nullable=false, precision=31, scale=8)
    public BigDecimal getAmtAcctCR() {
        return this.amtAcctCR;
    }
    
    public void setAmtAcctCR(BigDecimal amtAcctCR) {
        this.amtAcctCR = amtAcctCR;
    }

    
    @Column(name="FACT_ACCT_GROUP_ID", nullable=false, length=32)
    public String getFactAcctGroupId() {
        return this.factAcctGroupId;
    }
    
    public void setFactAcctGroupId(String factAcctGroupId) {
        this.factAcctGroupId = factAcctGroupId;
    }

    
    @Column(name="SEQNO", nullable=false)
    public int getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(int seqNo) {
        this.seqNo = seqNo;
    }




}


