/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.erp.acct.model.list.PeriodType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtPeriod generated by hbm2java
 */
@Entity
@Table(name="C_PERIOD"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"C_YEAR_ID", "NAME"}), @UniqueConstraint(columnNames={"C_YEAR_ID", "PERIODNO"})} 
)
public class FinancialMgmtPeriod  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_YEAR = "financialMgmtYear";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_PERIOD_NO = "periodNo";
     public static final String PROPERTY_PERIOD_TYPE = "periodType";
     public static final String PROPERTY_START_DATE = "startDate";
     public static final String PROPERTY_END_DATE = "endDate";

     private String id;
     private FinancialMgmtYear financialMgmtYear;
     private String name;
     private int periodNo;
     private PeriodType periodType;
     private Date startDate;
     private Date endDate;

    public FinancialMgmtPeriod() {
    }

	
    public FinancialMgmtPeriod(FinancialMgmtYear financialMgmtYear, String name, int periodNo, PeriodType periodType, Date startDate) {
        this.financialMgmtYear = financialMgmtYear;
        this.name = name;
        this.periodNo = periodNo;
        this.periodType = periodType;
        this.startDate = startDate;
    }
    public FinancialMgmtPeriod(FinancialMgmtYear financialMgmtYear, String name, int periodNo, PeriodType periodType, Date startDate, Date endDate) {
       this.financialMgmtYear = financialMgmtYear;
       this.name = name;
       this.periodNo = periodNo;
       this.periodType = periodType;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="C_PERIOD_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_YEAR_ID", nullable=false)
    public FinancialMgmtYear getFinancialMgmtYear() {
        return this.financialMgmtYear;
    }
    
    public void setFinancialMgmtYear(FinancialMgmtYear financialMgmtYear) {
        this.financialMgmtYear = financialMgmtYear;
    }

    
    @Column(name="NAME", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PERIODNO", nullable=false)
    public int getPeriodNo() {
        return this.periodNo;
    }
    
    public void setPeriodNo(int periodNo) {
        this.periodNo = periodNo;
    }

    
    @Column(name="PERIODTYPE", nullable=false, length=60)
    public PeriodType getPeriodType() {
        return this.periodType;
    }
    
    public void setPeriodType(PeriodType periodType) {
        this.periodType = periodType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STARTDATE", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENDDATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


