/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.erp.acct.model;
// Generated May 18, 2014 10:29:15 AM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * FinancialMgmtGLJournalLine generated by hbm2java
 */
@Entity
@Table(name="GL_JOURNALLINE"
)
public class FinancialMgmtGLJournalLine  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_FINANCIAL_MGMT_ACCOUNTING_COMBINATION = "financialMgmtAccountingCombination";
     public static final String PROPERTY_FINANCIAL_MGMT_G_L_JOURNAL = "financialMgmtGLJournal";
     public static final String PROPERTY_LINE = "line";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_AMT_ACCT_D_R = "amtAcctDR";
     public static final String PROPERTY_AMT_ACCT_C_R = "amtAcctCR";

     private String id;
     private FinancialMgmtAccountingCombination financialMgmtAccountingCombination;
     private FinancialMgmtGLJournal financialMgmtGLJournal;
     private int line;
     private String description;
     private BigDecimal amtAcctDR;
     private BigDecimal amtAcctCR;

    public FinancialMgmtGLJournalLine() {
    }

	
    public FinancialMgmtGLJournalLine(FinancialMgmtAccountingCombination financialMgmtAccountingCombination, FinancialMgmtGLJournal financialMgmtGLJournal, int line, BigDecimal amtAcctDR, BigDecimal amtAcctCR) {
        this.financialMgmtAccountingCombination = financialMgmtAccountingCombination;
        this.financialMgmtGLJournal = financialMgmtGLJournal;
        this.line = line;
        this.amtAcctDR = amtAcctDR;
        this.amtAcctCR = amtAcctCR;
    }
    public FinancialMgmtGLJournalLine(FinancialMgmtAccountingCombination financialMgmtAccountingCombination, FinancialMgmtGLJournal financialMgmtGLJournal, int line, String description, BigDecimal amtAcctDR, BigDecimal amtAcctCR) {
       this.financialMgmtAccountingCombination = financialMgmtAccountingCombination;
       this.financialMgmtGLJournal = financialMgmtGLJournal;
       this.line = line;
       this.description = description;
       this.amtAcctDR = amtAcctDR;
       this.amtAcctCR = amtAcctCR;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="GL_JOURNALLINE_ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_VALIDCOMBINATION_ID", nullable=false)
    public FinancialMgmtAccountingCombination getFinancialMgmtAccountingCombination() {
        return this.financialMgmtAccountingCombination;
    }
    
    public void setFinancialMgmtAccountingCombination(FinancialMgmtAccountingCombination financialMgmtAccountingCombination) {
        this.financialMgmtAccountingCombination = financialMgmtAccountingCombination;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GL_JOURNAL_ID", nullable=false)
    public FinancialMgmtGLJournal getFinancialMgmtGLJournal() {
        return this.financialMgmtGLJournal;
    }
    
    public void setFinancialMgmtGLJournal(FinancialMgmtGLJournal financialMgmtGLJournal) {
        this.financialMgmtGLJournal = financialMgmtGLJournal;
    }

    
    @Column(name="LINE", nullable=false)
    public int getLine() {
        return this.line;
    }
    
    public void setLine(int line) {
        this.line = line;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="AMTACCTDR", nullable=false, precision=31, scale=8)
    public BigDecimal getAmtAcctDR() {
        return this.amtAcctDR;
    }
    
    public void setAmtAcctDR(BigDecimal amtAcctDR) {
        this.amtAcctDR = amtAcctDR;
    }

    
    @Column(name="AMTACCTCR", nullable=false, precision=31, scale=8)
    public BigDecimal getAmtAcctCR() {
        return this.amtAcctCR;
    }
    
    public void setAmtAcctCR(BigDecimal amtAcctCR) {
        this.amtAcctCR = amtAcctCR;
    }




}


