/**
 * Copyright 2014 Fernando Rincon Martin <frm.rincon@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openeos.numeration.model;
// Generated Mar 13, 2014 8:43:01 PM by Hibernate Tools 4.0.0
// Template generated from org.openeos.hibernate.hbm2java


import org.openeos.numeration.model.list.NumerationResolverListItem;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name="nu_sequence"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name"), @UniqueConstraint(columnNames="value")} 
)
public class Sequence  implements java.io.Serializable {


     public static final String PROPERTY_ID = "id";
     public static final String PROPERTY_VALUE = "value";
     public static final String PROPERTY_NAME = "name";
     public static final String PROPERTY_DESCRIPTION = "description";
     public static final String PROPERTY_PATTERN = "pattern";
     public static final String PROPERTY_PATTERT_FOR_RESOLVER = "pattertForResolver";
     public static final String PROPERTY_NUMERATION_RESOLVER_ID = "numerationResolverId";
     public static final String PROPERTY_SEQUENCE_INSTANCE_LIST = "sequenceInstanceList";

     private String id;
     private String value;
     private String name;
     private String description;
     private String pattern;
     private String pattertForResolver;
     private NumerationResolverListItem numerationResolverId;
     private Set<SequenceInstance> sequenceInstanceList = new HashSet<SequenceInstance>(0);

    public Sequence() {
    }

	
    public Sequence(String value, String name, String pattern, NumerationResolverListItem numerationResolverId) {
        this.value = value;
        this.name = name;
        this.pattern = pattern;
        this.numerationResolverId = numerationResolverId;
    }
    public Sequence(String value, String name, String description, String pattern, String pattertForResolver, NumerationResolverListItem numerationResolverId, Set<SequenceInstance> sequenceInstanceList) {
       this.value = value;
       this.name = name;
       this.description = description;
       this.pattern = pattern;
       this.pattertForResolver = pattertForResolver;
       this.numerationResolverId = numerationResolverId;
       this.sequenceInstanceList = sequenceInstanceList;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="nu_sequence_id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="value", unique=true, nullable=false, length=40)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="name", unique=true, nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="pattern", nullable=false)
    public String getPattern() {
        return this.pattern;
    }
    
    public void setPattern(String pattern) {
        this.pattern = pattern;
    }

    
    @Column(name="patternforresolver")
    public String getPattertForResolver() {
        return this.pattertForResolver;
    }
    
    public void setPattertForResolver(String pattertForResolver) {
        this.pattertForResolver = pattertForResolver;
    }

    
    @Column(name="numeration_resolver_id", nullable=false)
    public NumerationResolverListItem getNumerationResolverId() {
        return this.numerationResolverId;
    }
    
    public void setNumerationResolverId(NumerationResolverListItem numerationResolverId) {
        this.numerationResolverId = numerationResolverId;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sequence")
    public Set<SequenceInstance> getSequenceInstanceList() {
        return this.sequenceInstanceList;
    }
    
    public void setSequenceInstanceList(Set<SequenceInstance> sequenceInstanceList) {
        this.sequenceInstanceList = sequenceInstanceList;
    }




}


